[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

#{{{ Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook-source = '''
  let g:go_fmt_autosave = 1
  let g:go_metalinter_excludes = ['.*\.pb\.go', '.*_mock\.go']
  let g:go_metalinter_deadline = '1m'
  let g:go_term_enabled = 1
  let g:go_gocode_autobuild = 0
  let g:go_gocode_unimported_packages = 1
  let g:go_highlight_array_whitespace_error = 1
  let g:go_highlight_chan_whitespace_error = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_space_tab_error = 1
  let g:go_highlight_trailing_whitespace_error = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_function_arguments = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_generate_tags = 1
  let g:go_highlight_string_spellcheck = 1
  let g:go_highlight_format_strings = 1
  let g:go_highlight_variable_declarations = 1
  let g:go_highlight_variable_assignments = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build =  'make'
#}}}

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_post_source = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-pathogen'

#{{{ Clang
[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']
#}}}

#{{{ Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'skwp/vim-rspec'
on_ft = 'ruby'

[[plugins]]
repo = 'Keithbsmiley/rspec.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'ngmy/vim-rubocop'
#}}}

#{{{ JSON
[[plugins]] # Preview
repo = 'elzr/vim-json'
on_ft = 'javascript'
#}}}

#{{{ TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
#}}}

#{{{ SQL
[[plugins]]
repo = 'vim-scripts/SQLUtilities'
on_ft = 'sql'

[[plugins]]
repo = 'vim-scripts/Align'
on_ft = 'sql'
#}}}
